const xoConfig = [
  {
    name: 'svgforge/options',
    space: true,
  },
  {
    name: 'svgforge/rules',
    files: ['**/*.{js,cjs,mjs}'],
    rules: {
      'arrow-body-style': 'off',
      'capitalized-comments': 'off',
      'eslint-comments/disable-enable-pair': 'off',
      'import/no-anonymous-default-export': 'off',
      'jsdoc/check-values': ['error', {allowedLicenses: ['MIT https://github.com/joeda1/svgforge/blob/main/LICENSE']}],
      'jsdoc/no-undefined-types': ['error', {definedTypes: ['SVGSpriter', 'File', 'SVGShape', 'SVGSprite', 'playwright', 'HTMLElement']}],
      'jsdoc/require-returns': 'error',
      'jsdoc/tag-lines': 'off',
      '@stylistic/no-trailing-spaces': 'off',
      'jsdoc/imports-as-dependencies': 'off',
      'jsdoc/informative-docs': 'off',
      'jsdoc/require-asterisk-prefix': 'off',
      'logical-assignment-operators': 'off',
      'max-depth': ['warn', 5],
      'max-params': 'off',
      'no-bitwise': 'off',
      eqeqeq: ['error', 'smart'],
      'no-eq-null': 'off',
      'no-shadow': 'off',
      'regexp/no-super-linear-move': 'off',
      'require-unicode-regexp': 'off',
      'unicorn/name-replacements': 'off',
      'unicorn/no-computed-property-existence-check': 'off',
      'unicorn/no-duplicate-loops': 'off',
      'unicorn/prefer-number-coercion': 'off',
      'unicorn/prefer-object-iterable-methods': 'off',
      'prefer-template': 'error',
      'spaced-comment': 'off',
      'unicorn/explicit-length-check': 'off',
      'unicorn/no-anonymous-default-export': 'off',
      'unicorn/no-array-method-this-argument': 'off',
      'unicorn/no-array-reduce': 'off',
      'unicorn/no-negated-condition': 'off',
      'unicorn/prefer-code-point': 'off',
      'unicorn/prefer-event-target': 'off',
      'unicorn/prefer-reflect-apply': 'off',
      'unicorn/prefer-string-slice': 'off',
      'unicorn/prevent-abbreviations': 'off',
      '@eslint-community/eslint-comments/require-description': 'off',
      'import-x/no-anonymous-default-export': 'off',
      'jsdoc/check-syntax': 'off',
      'jsdoc/require-description': 'off',
      'jsdoc/reject-any-type': 'off',
      'jsdoc/reject-function-type': 'off',
      'n/prefer-global/process': 'off',
      'node-test/no-export': 'off',
      'node-test/prefer-context-mock': 'off',
      'regexp/no-unused-capturing-group': 'off',
      'regexp/prefer-named-capture-group': 'off',
      'unicorn/consistent-class-member-order': 'off',
      'unicorn/error-message': 'off',
      'unicorn/logical-assignment-operators': 'off',
      'unicorn/max-nested-calls': 'off',
      'unicorn/no-array-callback-reference': 'off',
      'unicorn/no-array-sort': 'off',
      'unicorn/no-break-in-nested-loop': 'off',
      'unicorn/no-declarations-before-early-exit': 'off',
      'unicorn/no-duplicate-if-branches': 'off',
      'unicorn/no-for-each': 'off',
      'unicorn/no-global-object-property-assignment': 'off',
      'unicorn/no-top-level-side-effects': 'off',
      'unicorn/no-unsafe-string-replacement': 'off',
      'unicorn/prefer-object-define-properties': 'off',
      'unicorn/prefer-private-class-fields': 'off',
      'unicorn/prefer-ternary': 'off',
      'unicorn/require-array-sort-compare': 'off',
    },
  },
  {
    name: 'svgforge/test-overrides',
    files: ['test/**'],
    rules: {
      'jsdoc/require-returns': 'off',
    },
  },
  {
    name: 'svgforge/ignore-non-code',
    ignores: [
      '**/*.md',
      '**/*.json',
      '**/*.html',
      '**/*.svg',
      '**/*.yaml',
      '**/*.yml',
      '**/*.css',
      '**/*.scss',
      '**/*.mustache',
      '**/coverage/**',
      '**/docs/**',
      '**/tmpl/**',
      '**/test/tmpl/**',
      '**/test/fixture/**',
    ],
  },
];

export default xoConfig;
